apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-volume
  labels:
    name: mysql
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
#(작성중입니다)
